import shutil
import os
from os.path import join as pjoin
from config import HOME, BASE, CONFIG, ENV_URL,EMBED_WORK,HOST_NAME


def setup_tftp():
    shutil.copy(pjoin(BASE, 'tftp'),'/etc/xinetd.d/tftp')

def setup_export():
    fd = open('/etc/exports', 'a')
    fd.write('\n')
    fd.write("# Generated by env_init\n")
    fd.write("%s  *(rw,sync,no_root_squash) \n" % pjoin(HOME,EMBED_WORK))
    fd.close()

def do():
    setup_tftp()
    setup_export()
